### ISSUE TITLE
 criticalsection enter/leave missing in AddItem

### ISSUE THREAD

**Issue by dide2k** [daviladanielc/DelphiCacheControl#1]
Hello Daniel

I've only 'read' your code but if I'm not mistaken, I see no criticalsection enter/leave sequence in the ( important ) 'AddItem' ?
( like in GetItemByKey / DeleteItem... ) 
( private EnqueueCachedItem Item seems unused ) 

regards

**Comment by daviladanielc** [comment]
Hi, thank you for notifying me. I've just uploaded the fix.
